#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter



if __name__ == '__main__':
    s = input()
    pairs = Counter(s)
    pairs = sorted(dict(sorted(pairs.items())).items(), key=lambda x: x[1], reverse=True)[0:3]

    
    for i in range(3):
        print(pairs[i][0] + ' ' + str(pairs[i][1]))
    
