#!/bin/python3

import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

sen = ''

for i in range(m):
    for j in range(len(matrix)):
        sen += matrix[j][i]
# import re

# n, m = map(int, input().split())
# a, b = [], ""
# for _ in range(n):
#     a.append(input())

# for z in zip(*a):
#     b += "".join(z)

print(re.sub(r"(?<=\w)([^\w]+)(?=\w)", " ", sen))
    
